### ISSUE TITLE
After an unsubscription, should we keep users info on our servers even if he is not an user anymore? 

### ISSUE THREAD

**Issue by giovannicolonna** [PRIMETIME4U/PRIMETIME4U-server#45]

**Comment by Ionita** [comment]
I think we should keep users info for a period of time because maybe he will return to use the app and we want that this one will have all previous informations. Or maybe if a user that is unsubscribed and  want to be again subscribed, we can ask him if he want to have his previous informations or if he want to use app like the first time he's using it.
